cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<id>\d+)/$', views.CartAdd, name='CartAdd'),
]

myshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    # url(r'^cupons/', include('cupons.urls', namespace='cupon')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    # url(r'^payment/', include('payment.urls', namespace='payment')),

    # url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^', include('shop.urls', namespace='shop'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.OrderCreate, name='OrderCreate'),
]

shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.ProductList, name='ProductList'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from shop.models import Product
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator


class Order(models.Model):
    first_name = models.CharField(verbose_name='Имя', max_length=50)
    last_name = models.CharField(verbose_name='Фамилия', max_length=50)
    email = models.EmailField(verbose_name='Email')
    address =  models.CharField(verbose_name='Адрес', max_length=250)
    postal_code = models.CharField(verbose_name='Почтовый код', max_length=20)
    city = models.CharField(verbose_name='Город', max_length=100)
    created = models.DateTimeField(verbose_name='Создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Обновлен', auto_now=True)
    paid = models.BooleanField(verbose_name='Оплачен', default=False)

    class Meta:
        ordering = ('-created', )
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Заказ: {}'.format(self.id)

    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items')
    product = models.ForeignKey(Product, related_name='order_items')
    price = models.DecimalField(verbose_name='Цена', max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(verbose_name='Количество', default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Модель категории
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Имя')
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductListByCategory', args=[self.slug])


# Модель продукта
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', verbose_name="Категория")
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True, verbose_name="Изображение товара")
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    stock = models.PositiveIntegerField(verbose_name="На складе")
    available = models.BooleanField(default=True, verbose_name="Доступен")
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлен')

    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'slug']
        ]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductDetail', args=[self.id, self.slug])

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="Количество")
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code',
                  'city']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
# from cupons.forms import CuponApllyForm


@require_POST
def CartAdd(request, id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('cart:CartDetail')

def CartRemove(request, id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=id)
    cart.remove(product)
    return redirect('cart:CartDetail')

def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm({'quantity': item['quantity'],'update': True})

    return render(request, 'cart/detail.html', {'cart': cart})

orders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import OrderItem, Order
from .forms import OrderCreateForm
from cart.cart import Cart
from .tasks import OrderCreated
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
from django.http import HttpResponse


def OrderCreate(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            # if cart.cupon:
            #     order.cupon = cart.cupon
            #     order.discount = cart.cupon.discount
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()

            # Асинхронная отправка сообщения
            OrderCreated.delay(order.id)
            request.session['order_id'] = order.id
            return redirect(reverse('payment:process'))

    form = OrderCreateForm()
    return render(request, 'orders/order/create.html', {'cart': cart,
                                                        'form': form})

shop/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from .models import Category, Product
from cart.forms import CartAddProductForm


# Страница с товарами
def ProductList(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products
    })

# Страница товара
def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html',
                             {'product': product,
                              'cart_product_form': cart_product_form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %} {% block title %} Ваша корзина товаров {% endblock %} {% block content %}
<h1>Ваша корзина товаров</h1>

<div id="shopping-cart" class="shopping-cart">
<div class="shopping-cart-header">
  <i class="fa fa-shopping-cart cart-icon"></i><span class="badge">{{cart|length}}</span>
  <div class="shopping-cart-total">
    <span class="lighter-text">Total:{{ cart.get_total_price }} грн.</span>
  </div>
</div>
<!--end shopping-cart-header -->

<ul class="shopping-cart-items col-md-12">
  {% for item in cart %} {% with product=item.product %}
  <li style="list-style-type: none;" class='clearfix col-md-6'>
    <a href="{{ item.product.get_absolute_url }}"><img style="height: 200px;" src='{{ item.product.image.url }}' alt='{{ item.product.image.url }}' /></a>
    
    <span class='item-name'>{{ item.product.name }}</span><span class='item-price'>{{ item.price }} грн.</span>

    <form action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
      {{ item.update_quantity_form.quantity }} {{ item.update_quantity_form.update }} {% csrf_token %}
      <input type="submit" value="Обновить">
    </form>
    <br>
    <span class='item-price'>В сумме {{ item.total_price}} грн.</span>
    
    <!--<span class='item-quantity'>Quantity:1</span>-->
    <a style="padding: 0 15px;"  href="{% url "cart:CartRemove" product.id %}">
      <i style='font-size: 20px' class='delete_item_in_cart fa fa-trash-o'></i>
  </a>
</li>
  {% endwith %} {% endfor %}
</ul>

<p class="text-right">
      <a href="{% url "shop:ProductList"%}" class="btn">Продолжить Шопинг</a>
      <a href="{% url "orders:OrderCreate" %}" class="btn">Оформить заказ</a>
    </p>
</div>
<!--end shopping-cart -->

    


{% endblock %}

orders/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block title %}
  Оформление заказа
{% endblock %}

{% block content %}
  <h1>Оформление заказа</h1>
  <div class="col-sm-4">
    <h2>Заполните форму</h2>
    <form class="order-form" action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Отправить">
    </form>
  </div>

  <div class="order-info col-sm-8">
    <h2>Ваш заказ</h2>
    <ul>
      {% for item in cart  %}
        <li>
          {{ item.product.name }} | Количество: {{ item.quantity }} | Цена: {{ item.total_price }}
        </li>
      {% endfor %}
      {% if cart.cupon %}
        <li>
          "{{ cart.cupon.code }}" (на {{ cart.cupon.discount }}% меньше)
          <span> - {{ cart.get_discount|floatformat:"2"}} руб.</span>
        </li>
      {% endif %}
    </ul>
    <p><strong>Всего:</strong> {{ cart.get_total_price_after_discount|floatformat:"2"}} руб.</p>
  </div>
{% endblock %}

orders/templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block title %}
  Спасибо за заказ
{% endblock %}

{% block content %}
  <h1>Спасибо за заказ</h1>
  <p>Идентификатор вашего заказа: {{ order.id }}</p>
{% endblock %}

orders/templates/orders/order/pdf.html
<html>
  <body>
    <h1>Онлайн-магазин</h1>
    <p>
      Номер заказа: <b>{{ order.id }}</b> <br>
      <span class="secondary">
        {{ order.created }}
      </span>
    </p>
    <h3>Покупатель</h3>
    <p>
      {{ order.first_name }} {{ order.last_name }}<br>
      {{ order.email }} <br>
      {{ order.address }} <br>
      {{ order.postal_code }}, {{ order.city }}
    </p>
    <h3>Купленные товары</h3>
    <table class="table">
      <thead>
        <tr>
          <th>Товар</th>
          <th>Стоймость</th>
          <th>Количество</th>
          <th>Всего</th>
        </tr>
      </thead>
      <tbody>
        {% for item in order.items.all %}
          <tr class="row{% cycle "1" "2" %}">
            <td>{{ item.product.name }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.get_cost }}</td>
          </tr>
        {% endfor %}
        <tr class="total">
          <td colspan="3">Всего:</td>
          <td class="num">{{ order.get_total_cost }}</td>
        </tr>
      </tbody>
    </table>
    <span class="{% if order.paid %}paid{% else %}pending{% endif %}">
      {% if order.paid %}Оплачен{% else %}Ожидает оплаты{% endif %}
    </span>
  </body>
</html>

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>{%block title%}{%endblock%}</title>
  <!-- Styles -->
  {%load static%}
  <link rel="stylesheet" href="{% static "/css/style.css" %}">
  <link rel="stylesheet" href="{% static "/css/bootstrap.min.css" %}">

  
</head>

<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
        <a href="/" class="navbar-brand">MyShop</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <!--<li><a href="{% url 'shop:ProductList' %}">Categories</a></li>-->
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {%with total_items=cart|length%} {%if cart|length > 0%}
          <li><a href="{% url "cart:CartDetail" %}"><i style="color:white" class="fa fa-shopping-cart cart-icon"></i> Корзина <span style="background-color:white;color: black;" class="badge">{{ total_items }}</span> {{ cart.get_total_price }} грн{%else %}<li><a href="/"><i style="color:white" class="fa fa-shopping-cart cart-icon"></i>Корзина пустая</a></li>{%endif%} {%endwith%}</a>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div id="content" style="padding-top: 50px;" class="container body-content">
    <div class="row">
      <div class="col-md-6 col-lg-12">
        {% block content %}{% endblock %}
      </div>
    </div>
    <hr/>
    <footer>
      <p>&copy; Application</p>
    </footer>
  </div>

</body>

</html>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}

{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <div class="col-sm-6">
      <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
    </div>
    <div class="col-sm-6">
      <h1>{{ product.name }}</h1>
      <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
      <p class="price">{{ product.price }} грн.</p>
      <form action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Добавить в корзину">
      </form>
      <span>{{ product.description | linebreaks}}</span>
    </div>
  </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
  {% if category %} {{ category.name }} {% else %} Товары {% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar" class="col-sm-3">
    <h3>Категории</h3>
    <ul>
      <li {% if not category %} class="selected" {% endif %}>
        <a href="{% url "shop:ProductList" %}">Все</a>
      </li>
      {% for cat in categories %}
        <li {% if category.slug == cat.slug %} class="selected" {% endif %}>
          <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product_list col-sm-9">
    <h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
    <div class="items row">
      {% for product in products %}
        <div class="item col-sm-4">
          <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
          </a>
          <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
          {{ product.price }} грн.
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}